### PR TITLE
s/notPr0d/admin1/ for dataverseAdmin password #44

### LINKED ISSUE #44: Install Script - Default credentials are different
The default credentials are different depending on which install script you use. As a first time deployer of the ansible version on AWS, I had to ask around to those with more experience to learn the default `dataverseAdmin` password is different.

### PR DESCRIPTION
**Pull request by pdurbin**
Fixes #44 

admin1 is what @mheppler and I use on "phoenix" and other servers.

See also https://github.com/IQSS/dataverse/issues/4178

Please note that I left the Glassfish password as notPr0d. I don't care what that password is. 😄

### CODE REVIEW

**Comment by atc0005** [comment]
FWIW, we were caught off guard by this to begin with until we paid attention to the default password in the role being different than what normal installation doc listed as the initial admin password. Having both sets of default values the same should help reduce any confusion.

**Comment by pdurbin** [comment]
> different than what normal installation doc listed as the initial admin password

Well, to be clear, the installation doc has "admin" and our phoenix server uses "admin1". For the history on this, please see https://github.com/IQSS/dataverse/issues/4178

**Comment by atc0005** [comment]
> Well, to be clear, the installation doc has "admin" and our phoenix server uses "admin1". For the history on this, please see [IQSS/dataverse#4178](https://github.com/IQSS/dataverse/issues/4178)

My bad, I misread the intent. Ignore my ramblings.

**Comment by pdurbin** [comment]
@atc0005 heh. No it's fine. In fact, I think we should use "admin1" everywhere, even in the installation guide. Everybody knows you should change the password after you install software like Dataverse. It's irritating to have to change the password from "admin". If you think it should be "admin1" everywhere, please feel free to open an issue over at https://github.com/IQSS/dataverse/issues . If not, no worries, no pressure. 😄 Thanks for trying Dataverse!

**Comment by atc0005** [comment]
> If you think it should be "admin1" everywhere, please feel free to open an issue over at https://github.com/IQSS/dataverse/issues

Done!

**Pull request merged**
