### PR TITLE
#39 make jdk version configurable

### PR DESCRIPTION
**Pull request by donsizemore**

### CODE REVIEW

**Comment by donsizemore** [comment]
@pdurbin if you're trying this one first I'll need to tidy up one file in PR #41 to prevent a minor merge conflict before you test #41.

**Comment by pdurbin** [comment]
@donsizemore unfortunately, I think I'm already dead in the water. From what I can tell, Glassfish doesn't run on Java 11. For some links I found, please check out https://github.com/IQSS/dataverse/issues/5512#issuecomment-462957172

**Comment by donsizemore** [comment]
@pdurbin scope creep. this issue was to enable a configurable java version for development/experimentation, and still defaults to 1.8. glassfish/payara config would go in a separate issue.

**Comment by pdurbin** [comment]
@donsizemore good point, especially how the default is still Java 8. I merged it. I think we should keep #39 open until we're actually using Java 11 though.

**Pull request merged**
