### PR TITLE
111 centos 8

### PR DESCRIPTION
**Pull request by donsizemore**
rhel/centos8 requires postgresql10+; everything else required only minor tweaks.

### CODE REVIEW

**Comment by pdurbin** [comment]
@donsizemore I looked as of e146bd6 and this pull request is looking good. Should we include in this pull request change to ec2-create-instance.sh where we add a switch for which AMI to spin up?

**Comment by donsizemore** [comment]
@pdurbin let's make that a separate issue/PR? it'll require two flags, one to choose the AMI and one to choose the size (not all size/AMI combos play together)

**Comment by pdurbin** [comment]
@donsizemore that's fine. I'm happy to create the issues about AMI selection etc. For this pull request I'm fine with you just merging it if you're feeling pretty good about it. We can always back it out if things go sideways. 😄

**Comment by pdurbin** [comment]
@donsizemore you have my blessing to merge. 😄

**Pull request merged**
