### PR TITLE
#60 enable data explorer

### PR DESCRIPTION
**Pull request by donsizemore**

### CODE REVIEW

**Comment by pdurbin** [comment]
@donsizemore thank you very much for working on this!

I just went to http://ec2-3-84-169-65.compute-1.amazonaws.com:8080/file.xhtml?fileId=11&datasetVersionId=2 and tried to launch Data Explorer but I think it didn't work because...

- port 8080 is missing from `siteUrl` in https://scholarsportal.github.io/Dataverse-Data-Explorer/?fileId=11&siteUrl=http://ec2-3-84-169-65.compute-1.amazonaws.com
- SSL isn't enabled on my EC2 instance

... or both? I'm not sure. Here are some screenshots:

Screen Shot 2019-07-09 at 11 43 03 AM
Screen Shot 2019-07-09 at 11 43 22 AM
Screen Shot 2019-07-09 at 11 43 48 AM

**Comment by pdurbin** [comment]
The JVM option doesn't have the port in it:

```
[glassfish@ip-172-31-34-129 ~]$ /usr/local/glassfish4/bin/asadmin list-jvm-options | grep siteUrl
-Ddataverse.siteUrl=http://ec2-3-84-169-65.compute-1.amazonaws.com
[glassfish@ip-172-31-34-129 ~]$ 
```

I'll try adding it and restarting Glassfish.

**Comment by pdurbin** [comment]
Adding port 8080 to `siteUrl` didn't help. It still hangs:

Screen Shot 2019-07-09 at 12 01 38 PM

**Comment by pdurbin** [comment]
curl -k https://localhost:8181/api/info/version works...

{"status":"OK","data":{"version":"4.15","build":"221-9a0b627"}}

But curl https://ec2-3-84-169-65.compute-1.amazonaws.com:8181/api/info/version does not:

curl: (7) Failed to connect to ec2-3-84-169-65.compute-1.amazonaws.com port 8181: Operation timed out

I tried dropping the firewall:

```
[root@ip-172-31-34-129 ~]# service iptables stop
Redirecting to /bin/systemctl stop iptables.service
Failed to stop iptables.service: Unit iptables.service not loaded.
[root@ip-172-31-34-129 ~]# 
```

I have to run to the annual IQSS BBQ but I'd like to be able to get to port 8181 on HTTPS from my browser. I'm find with accepting a self signed cert if necessary.

**Comment by pdurbin** [comment]
Now I'm running 3a548c4 and started at http://ec2-52-201-217-101.compute-1.amazonaws.com/file.xhtml?fileId=11&datasetVersionId=2 (no port 8080) but mixed content is blocked:

Screen Shot 2019-07-09 at 2 28 38 PM

Screen Shot 2019-07-09 at 2 28 50 PM

**Comment by donsizemore** [comment]
ah ah I was wondering whether I needed to enable CORS but didn't (since in this case we point at Scholars' Portal). will fix.

**Comment by pdurbin** [comment]
Ok, if I set my siteUrl to https like this: `<jvm-options>-Ddataverse.siteUrl=https://ec2-52-201-217-101.compute-1.amazonaws.com</jvm-options>`

And if I start at https://ec2-52-201-217-101.compute-1.amazonaws.com/file.xhtml?fileId=11&datasetVersionId=2 (https, no port), I make progress but there are no summary statistics or graphs:

Screen Shot 2019-07-09 at 2 38 46 PM
Screen Shot 2019-07-09 at 2 38 50 PM
Screen Shot 2019-07-09 at 2 39 00 PM

I expect it to look more like this:

Screen Shot 2019-07-09 at 2 41 53 PM


So maybe I'm missing some R dependencies or something? I'm not sure what's going on.

**Pull request merged**
