### PR TITLE
WIP: Integrate Travis CI for testing

### PR DESCRIPTION
**Pull request by danschmidt5189**
It turns out that running systemd inside of CentOS inside of Docker inside of Travis is not quite as simple as you'd think:

- Travis builds run in Ubuntu, with no option for running on CentOS to begin with. Perhaps CircleCI is a better fit?
- We need CentOS7 + systemd + firewalld in order to test the role.

This takes an ugly first stab at it:

- Extends the centos:7 image to include systemd (for firewalld) and ansible
- Runs that image with our role/tests mounted inside
- Execs Ansible to "syntax-check" the test playbook
- Execs Ansible inside the container a la Vagrant's ansible_local provisioner

We could do something fancier with [Molecule](https://github.com/metacloud/molecule), but for now I just wanted to run something simple and easy.

> **Warning:** Builds currently timeout on the "install Shibboleth RPMs for RedHat/CentOS7" task. This also hangs for me in Vagrant, so I think it's likely a (hopefully, temporary) issue with the repository.

@pdurbin feel free to take over the PR if you feel like throwing some time at it! I have some home improvement projects to attend to before getting back to "work work" during the week. 😅

### CODE REVIEW

**Comment by pdurbin** [comment]
@danschmidt5189 thanks for this pull request! I went ahead and clicked "Activate this Repository" over at https://travis-ci.org/IQSS/dataverse-ansible and here some screenshots from what I saw:

## Before

screen shot 2018-03-04 at 6 02 40 pm

## After

screen shot 2018-03-04 at 6 02 59 pm

Let's get a pulse from @donsizemore before merging. @pameyer and others might be interested in taking a look as well. Thanks again!

**Comment by pameyer** [comment]
@danschmidt5189 good job figuring the systemd in docker bit out (for anyone else wondering, that's why the `cgroup` is a docker volume).

One suggestion - it might be useful to check `api/info/version` after the role runs to make sure that it's got a working dataverse installation.  

I'm pretty sure you're right about the shibboleth RPM timeouts - those seem to happen every so often; at least sometimes needing a bump in the shibboleth version.

**Comment by pdurbin** [comment]
I put a but in @donsizemore 's ear about this pull request this morning at http://irclog.iq.harvard.edu/dataverse/2018-03-12#i_64567

**Comment by pdurbin** [comment]
Merged! Let's continue the discussion at https://github.com/IQSS/dataverse-ansible/issues/14#issuecomment-372438024

**Pull request merged**
